package com.fil.rouge.emuns;

public enum Categories {

    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    GRAPHIC_DESIGN,
    DIGITAL_MARKETING,
    CONTENT_WRITING,
    VIDEO_EDITING,
    VIRTUAL_ASSISTANCE,
    TRANSLATION,
    DATA_ANALYSIS,
    VOICE_OVER,
    UI_UX_DESIGN,
    SOFTWARE_DEVELOPMENT,
    ECOMMERCE,
    BUSINESS_CONSULTING,
    AUDIO_PRODUCTION,
    PHOTOGRAPHY
}
